[package]
name = "tedwm"
version = "0.1.0"
authors = ["bryal <96.bryal@gmail.com>"]

[features]
default = []
profiling = ["cpuprofiler"]

[dependencies]
clap = "2.20"
futures = "0.1.11"
termion = "1.2"
tokio-timer = "0.1"
unicode-segmentation = "1.1"
unicode-width = "0.1"

cpuprofiler = { version = "0.0", optional = true }